<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Subscribe</name>
   <tag></tag>
   <elementGuidId>dbd6f199-bef3-4578-832d-6692285c155d</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pricing-page&quot;]/section[@class=&quot;pricing section section-on-bg&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;price-cols row&quot;]/div[@class=&quot;items-wrapper col-md-10 col-sm-12 col-xs-12 col-md-offset-1 col-sm-offset-0 col-xs-offset-0&quot;]/div[@class=&quot;item price-22 col-md-4 col-sm-4 col-xs-12 text-center best-buy&quot;]/div[@class=&quot;item-inner&quot;]/div[@class=&quot;content&quot;]/a[@class=&quot;btn btn-primary2 btn-block&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sandbox.vsms.tezzasolutions.com/signup?plan=tier2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary2 btn-block </value>
   </webElementProperties>
</WebElementEntity>
