<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Leave a message in unscheduled Visit</description>
   <name>leave a messsage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-10-12T09:51:58</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b8063b79-8137-4447-9821-1c49d8f3727b</testSuiteGuid>
   <testCaseLink>
      <guid>0d7fb508-369f-4638-b801-810cb729e9c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Self-Service Management/UnScheduled Visit/Leave Message in Unscheduled Visit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Leave a Message</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>ecf1b70c-53f7-43cb-a0c5-25f33c09a806</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>b1952b65-ee8f-44ee-8403-5b864ae90107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>4b8ce29a-badc-4b35-a9ec-6283b770b2c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>staffFullName</value>
         <variableId>1afcb50b-d048-4761-a878-1955eb4abc9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4d66d5a-a3f6-4fe2-9eda-3f603ebbae6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comment</value>
         <variableId>7e8b3299-1ade-4d54-b507-bfef095b9e39</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
