<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <integratedEntity>
      <productName>qTest</productName>
      <properties>
         <entry>
            <key>0</key>
            <value>{'parent':{'parentName':'','name':'VSMS Regression Testing','id':0,'type':6,'parentId':0},
'default':true,'name':'Login','pid':'TS-13','id':1437161,'testRuns':[]}</value>
         </entry>
      </properties>
      <type>TESTSUITE</type>
   </integratedEntity>
   <isRerun>false</isRerun>
   <lastRun>2017-10-24T12:32:25</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0e91638f-6d48-443c-a9c4-18ee6639ca33</testSuiteGuid>
   <testCaseLink>
      <guid>4404305c-e9e2-4e78-939f-a66766636e01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Module/Test Login</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>07b7fcfc-60ce-4a16-a086-6c9b8416eaba</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-3</value>
         </iterationEntity>
         <testDataId>Data Files/Login Credentials</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>07b7fcfc-60ce-4a16-a086-6c9b8416eaba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Loginemail</value>
         <variableId>42143b0e-2ca2-4be5-b67b-09df69774589</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>07b7fcfc-60ce-4a16-a086-6c9b8416eaba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>094464f7-d019-4fc9-aaa1-c891fcd44ba7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
